No Data animation showing in case of empty data from API response
alirezaeiii/TMDb-Compose-Paging3-Playground pull request #6
Opened 2024-06-10 13:12 UTC by AbdulRehmanNazar

No Data animation showing when there is empty data coming from API response.

https://github.com/alirezaeiii/TMDb-Compose-Playground/assets/6792823/8c674afe-03ed-4f8c-bd08-025d606c9f37

2024-06-10 21:06 UTC, alirezaeiii commented on buildSrc/src/main/java/Dependencies.kt
> -    const val composeConstraintLayout = "androidx.constraintlayout:constraintlayout-compose:${Versions.constraint_layout}"
Is there any reason you add a space here?

2024-06-10 21:07 UTC, alirezaeiii commented on buildSrc/src/main/java/Dependencies.kt
> -    const val lifecycleViewModel = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.lifecycle}"
And here also.

2024-06-10 21:09 UTC, alirezaeiii commented on features/feature-paging/src/main/java/com/sample/tmdb/paging/search/SearchScreens.kt
> +
And space here.

2024-06-10 21:09 UTC, alirezaeiii commented on features/feature-paging/src/main/java/com/sample/tmdb/paging/search/SearchScreens.kt
> +
Space here

2024-06-10 21:11 UTC, alirezaeiii requested changes
Your idea is very interesting. Thank you for your contribution. If you have any other idea, please feel free to open a PR.

2024-06-10 21:12 UTC, alirezaeiii commented on buildSrc/src/main/java/Dependencies.kt
> +    const val composeConstraintLayout =
Is there any reason you add a space here?

2024-06-10 21:12 UTC, alirezaeiii commented on buildSrc/src/main/java/Dependencies.kt
> +    const val lifecycleViewModel =
And here.

2024-06-11 01:33 UTC, AbdulRehmanNazar commented
Thanks for your feedback. some of the spaces are auto generated by studio, not its reset.
please go ahead and check and let me know if there is any issue any
Love to solve them

2024-06-11 04:58 UTC, alirezaeiii approved these changes

2024-06-11 05:01 UTC, merged

2024-06-11 05:12 UTC, alirezaeiii commented
> @alirezaeiii Thanks for your feedback. some of the spaces are auto generated by studio, not its reset. please go ahead and check and let me know if there is any issue any Love to solve them

Approved, Thanks again, Feel free to share any other new idea.